In [71]:
# Importing the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [72]:
#Importing Dataset
df = pd.read_csv('BankCustomers.csv')

In [73]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [74]:
X = df.iloc[:, 3:13]
y = df.iloc[:, 13]

In [75]:
X

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  
0             1               1        101348.88  
1             0               1        112542.58  
2             1               0        113931.57  
3             0               0         93826.63  
4             1               1         79084.10  
...         ...             ...              ...  
9995          1               0         96270.64  
9996          1               1        101699.77  
9997          0               1         42085.58  
9998          1               0         92888.52  
9999          1               0         38190.78  

[10000 rows x 10 columns]

In [76]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [77]:
#converging into dummy variables
state = pd.get_dummies(X['Geography'],drop_first=True)
gender = pd.get_dummies(X['Gender'],drop_first=True)

In [78]:
#concatenating dummy variables
X = pd.concat([X,state,gender],axis=1)

In [79]:
X = X.drop(['Geography','Gender'],axis=1)

In [80]:
#train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [81]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [82]:
# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Dropout

In [83]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform"))

# Adding the second hidden layer
classifier.add(Dense(activation="relu", units=6, kernel_initializer="uniform"))

# Adding the output layer
classifier.add(Dense(activation="sigmoid", units=1, kernel_initializer="uniform"))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
700/700 [==============================] - 1s 445us/step - loss: 0.4931 - accuracy: 0.7967
Epoch 2/100
700/700 [==============================] - 0s 449us/step - loss: 0.4297 - accuracy: 0.7977
Epoch 3/100
700/700 [==============================] - 0s 446us/step - loss: 0.4248 - accuracy: 0.7977
Epoch 4/100
700/700 [==============================] - 0s 440us/step - loss: 0.4213 - accuracy: 0.7977
Epoch 5/100
700/700 [==============================] - 0s 438us/step - loss: 0.4180 - accuracy: 0.8207
Epoch 6/100
700/700 [==============================] - 0s 435us/step - loss: 0.4160 - accuracy: 0.8227
Epoch 7/100
700/700 [==============================] - 0s 442us/step - loss: 0.4145 - accuracy: 0.8280
Epoch 8/100
700/700 [==============================] - 0s 434us/step - loss: 0.4134 - accuracy: 0.8290
Epoch 9/100
700/700 [==============================] - 0s 444us/step - loss: 0.4120 - accuracy: 0.8301
Epoch 10/100
700/700 [==============================] - 0s 444us/step - l

700/700 [==============================] - 0s 480us/step - loss: 0.3924 - accuracy: 0.8369
Epoch 80/100
700/700 [==============================] - 0s 481us/step - loss: 0.3925 - accuracy: 0.8366
Epoch 81/100
700/700 [==============================] - 0s 603us/step - loss: 0.3925 - accuracy: 0.8374
Epoch 82/100
700/700 [==============================] - 0s 565us/step - loss: 0.3924 - accuracy: 0.8361
Epoch 83/100
700/700 [==============================] - 1s 762us/step - loss: 0.3926 - accuracy: 0.8380
Epoch 84/100
700/700 [==============================] - 0s 426us/step - loss: 0.3923 - accuracy: 0.8346
Epoch 85/100
700/700 [==============================] - 0s 430us/step - loss: 0.3926 - accuracy: 0.8370
Epoch 86/100
700/700 [==============================] - 0s 434us/step - loss: 0.3921 - accuracy: 0.8381
Epoch 87/100
700/700 [==============================] - 0s 428us/step - loss: 0.3920 - accuracy: 0.8381
Epoch 88/100
700/700 [==============================] - 0s 514us/step - loss:

In [84]:
#predicting Test set results 
y_pred = classifier.predict(X_test)

In [85]:
y_pred

array([[0.23246303],
       [0.33678138],
       [0.17383626],
       ...,
       [0.17513144],
       [0.09448397],
       [0.5226925 ]], dtype=float32)

In [86]:
y_pred = (y_pred>0.5)

In [87]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [ True]])

In [88]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)

In [89]:
cm

array([[2270,  109],
       [ 332,  289]], dtype=int64)

In [90]:
accuracy

0.853